#!/bin/bash
# Builds SM64's sound data for THIS target (little-endian, 32-bit pointers)
# into build/sound_le/ (or $OUT), without touching the decomp's own (big-endian, N64)
# build/us/sound/:
#
#   sound_data.ctl  sound banks: instruments, envelopes, ADPCM books  (endian-dependent)
#   sound_data.tbl  ADPCM sample data                                 (byte stream)
#   sequences.bin   sequence table + .m64 sequences                    (table endian-dependent)
#   bank_sets       sequence -> bank map
#
# and from them:
#   sound_data_le.c   gSoundDataADSR / gSoundDataRaw / gMusicData /
#                     gBankSetsData as C arrays (the host sim links this);
#   sound.bin         the four blobs packed, 16-byte aligned: the game file's
#                     SND0 block, which the game loads to SOUND_BASE at boot;
#   sound_syms.ld     the four symbols at SOUND_BASE + their offsets, for the
#                     firmware link (INCLUDEd by linker/c-linker.ld).
#
# BITWIDTH=64 builds the variant the 64-bit host sim needs (pointer fields in
# the bank data are pointer-sized) into build/sound_le64/.
#
# The decomp's sample .aifc files (build/us/sound/samples) are reused as they
# are: they are the encoded samples, not target data. The one sequence that is
# assembly source (00_sound_player.s) only emits .byte directives, so this
# target's assembler builds it as well as MIPS as would.
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
SM64_DIR="${SM64_DIR:-$HERE/decomp}"
VERSION="${SM64_VERSION:-us}"
BITWIDTH="${BITWIDTH:-32}"
OUT="${OUT:-$HERE/build/sound_le$([ "$BITWIDTH" = 64 ] && echo 64 || true)}"
SOUND_BASE="${SOUND_BASE:-0x41700000}"
CROSS="${CROSS:-riscv-none-elf-}"
DEFS="-DVERSION_US=1 -DF3D_OLD=1 -D_FINALROM=1"
EB="--endian little --bitwidth $BITWIDTH"
mkdir -p "$OUT/seq"
cd "$SM64_DIR"

# The decomp's assemble_sound.py has a "/\*" in a plain string literal, which
# newer Pythons warn about (SyntaxWarning). The decomp stays unmodified, so
# the warning is silenced here instead.
PY="python3 -W ignore::SyntaxWarning"

# 1. Banks + samples.
$PY tools/assemble_sound.py "build/$VERSION/sound/samples/" sound/sound_banks/ \
    "$OUT/sound_data.ctl" "$OUT/ctl_header" "$OUT/sound_data.tbl" "$OUT/tbl_header" $DEFS $EB

# 2. Sequences: the .m64 files as extracted, plus 00_sound_player assembled here.
"${CROSS}gcc" -x assembler-with-cpp -c -I include -I "build/$VERSION" $DEFS \
    sound/sequences/00_sound_player.s -o "$OUT/seq/00_sound_player.o"
"${CROSS}objcopy" -j .rodata -O binary "$OUT/seq/00_sound_player.o" "$OUT/seq/00_sound_player.m64"
$PY tools/assemble_sound.py --sequences "$OUT/sequences.bin" "$OUT/sequences_header" "$OUT/bank_sets" \
    sound/sound_banks/ sound/sequences.json \
    "$OUT/seq/00_sound_player.m64" sound/sequences/$VERSION/*.m64 $DEFS $EB

# 3. One C file with the four blobs. 16-byte alignment: load.c DMAs them in
#    16-byte units and patches u32 fields in place.
{
    echo "/* generated by tools/build_sound_le.sh -- do not edit */"
    for pair in "gSoundDataADSR sound_data.ctl" "gSoundDataRaw sound_data.tbl" \
                "gMusicData sequences.bin" "gBankSetsData bank_sets"; do
        set -- $pair
        echo "__attribute__((aligned(16))) unsigned char $1[] = {"
        od -An -v -tu1 "$OUT/$2" | awk '{ for (i = 1; i <= NF; i++) printf "%s,", $i; print "" }'
        echo "};"
        echo "unsigned int ${1}_len = sizeof $1;"
    done
} > "$OUT/sound_data_le.c"
# 4. sound.bin + the linker symbols for it.
python3 - "$OUT" "$SOUND_BASE" <<'PY'
import sys
out, base = sys.argv[1], int(sys.argv[2], 0)
blob, syms = b"", []
for sym, f in [("gSoundDataADSR", "sound_data.ctl"), ("gSoundDataRaw", "sound_data.tbl"),
               ("gMusicData", "sequences.bin"), ("gBankSetsData", "bank_sets")]:
    blob += b"\0" * (-len(blob) % 16)
    syms.append("%s = 0x%08x;" % (sym, base + len(blob)))
    blob += open(f"{out}/{f}", "rb").read()
open(f"{out}/sound.bin", "wb").write(blob)
open(f"{out}/sound_syms.ld", "w").write(
    "/* generated by tools/build_sound_le.sh: sound.bin is loaded to 0x%08x */\n" % base
    + "\n".join(syms) + "\nSOUND_DATA_END = 0x%08x;\n" % (base + len(blob)))
PY
ls -l "$OUT"/sound_data.ctl "$OUT"/sound_data.tbl "$OUT"/sequences.bin "$OUT"/bank_sets "$OUT"/sound.bin
cat "$OUT"/sound_syms.ld
